### ISSUE TITLE
Unable To View Demo Via https://disaster-watch.netlify.com/

### ISSUE THREAD

**Issue by jerrychong25** [mepa1363/disaster-watch-frontend#25]
Hi @mepa1363 ,

Good day.

I'm interested to view demo for your project.

Unfortunately, the website no longer working now as of 13rd February 2023, as per following screenshot:
![image](https://user-images.githubusercontent.com/15714095/218406883-46edfb28-74b8-4b01-843a-510b4938d766.png)

Do you mind to share if there is a way to fix it or other website that can access working version of your demo?

Related issues:
- https://github.com/khordoo/disaster-watch-classifier/issues/20

Thank you.

**Comment by mepa1363** [comment]
@jerrychong25 Thanks for your interest in this project :) the reason why it does not work is that the backend services are not up and running. Take a look at [this doc](https://docs.google.com/document/d/15BGGFOvMZq2P_QHmKbe71MpBv1wMuFbJ15RlEkapnEs/edit) to understand what components are required for this project to run. The code for frontend, backend, and machine learning model are all on GitHub so you can run it yourself :)

**Comment by jerrychong25** [comment]
> @jerrychong25 Thanks for your interest in this project :) the reason why it does not work is that the backend services are not up and running. Take a look at [this doc](https://docs.google.com/document/d/15BGGFOvMZq2P_QHmKbe71MpBv1wMuFbJ15RlEkapnEs/edit) to understand what components are required for this project to run. The code for frontend, backend, and machine learning model are all on GitHub so you can run it yourself :)

Hi @mepa1363 ,

Thanks for the response.

The Youtube link in the doc solved the demo issue.

I just have one question to double confirm. 

In order to get many tweets and display it on frontend, bascially we just open disaster watch website and let it run idle for few hours without doing anythings?

Just to ensure my end able to replicate same result when troubleshooting.

Thank you in advance!

**Comment by mepa1363** [comment]
Yes, you can do that. Keep in mind that when you have the browser open for a while there will be a lot of data, which may cause your browser to crash.

**Comment by jerrychong25** [comment]
> Yes, you can do that. Keep in mind that when you have the browser open for a while there will be a lot of data, which may cause your browser to crash.

Hi @mepa1363 ,

Noted with thanks!
